import 'package:flutter/material.dart';

import '../../app/routes.dart';
import '../../core/errors/app_failure.dart';
import '../../core/theme/app_tokens.dart';
import '../../core/widgets/app_icons.dart';
import '../../core/widgets/buttons.dart';
import '../../core/widgets/chips.dart';
import '../../core/widgets/states.dart';
import '../../core/widgets/stroke_icon.dart';
import '../../core/widgets/toast.dart';
import '../../data/app_state.dart';

/// The consent gate every AI action passes through (prompt 02 §G.1).
///
/// Returns true when the caller may proceed: the layer is on, the parent
/// has accepted the current consent version, at least one key exists, and
/// the phone is online. Each miss is explained rather than swallowed.
Future<bool> ensureAiReady(BuildContext context) async {
  final state = AppScope.read(context);
  if (!state.aiAvailable) return false;

  final root = Navigator.of(context, rootNavigator: true);
  if (!state.aiConsented) {
    final accepted = await root.pushNamed<bool>(Routes.aiConsent) ?? false;
    if (!accepted || !context.mounted) return false;
  }

  if (!state.aiKeys.isLoaded) await state.aiKeys.load();
  if (!context.mounted) return false;

  if (state.aiKeys.keys.isEmpty) {
    AppToast.show(
      context,
      title: 'Add a Gemini key first',
      description: 'Paste a free Google AI Studio key in More → AI.',
      kind: ToastKind.warn,
      actionLabel: 'Open',
      onAction: () => root.pushNamed(Routes.aiSettings),
    );
    return false;
  }

  if (state.isOffline) {
    AppToast.failure(
      context,
      const AppFailure(
        FailureKind.offline,
        'Generating needs an internet connection.',
      ),
      title: "You're offline",
    );
    return false;
  }
  return true;
}

/// Small "AI" pill for records and artefacts the model produced.
class AiBadge extends StatelessWidget {
  const AiBadge({super.key, this.label = 'AI'});

  final String label;

  @override
  Widget build(BuildContext context) {
    final k = context.t;
    return StatusPill(
      label: label,
      background: k.priC,
      foreground: k.priInk,
      leading: StrokeIcon(AppIcons.sparkle, size: 12, color: k.priInk, strokeWidth: 2),
    );
  }
}

/// The banner on every AI-produced screen: what this is, and that the
/// parent checks it.
class AiNotice extends StatelessWidget {
  const AiNotice(this.text, {super.key, this.model});

  final String text;
  final String? model;

  @override
  Widget build(BuildContext context) {
    final k = context.t;
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 11),
      decoration: BoxDecoration(
        color: k.priC,
        borderRadius: BorderRadius.circular(14),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 1),
            child: StrokeIcon(AppIcons.sparkle, size: 18, color: k.priInk),
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  text,
                  style: TextStyle(
                    fontSize: 13,
                    height: 1.4,
                    fontWeight: FontWeight.w600,
                    color: k.priInk,
                  ),
                ),
                if (model != null && model!.isNotEmpty) ...[
                  const SizedBox(height: 2),
                  Text(
                    'Generated by $model',
                    style: TextStyle(fontSize: 11.5, color: k.priInk2),
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// "92%" / "Check" — how sure the model was about one row.
class ConfidencePill extends StatelessWidget {
  const ConfidencePill(this.confidence, {super.key, this.forceReview = false});

  final double confidence;
  final bool forceReview;

  @override
  Widget build(BuildContext context) {
    final k = context.t;
    final low = forceReview || confidence < 0.75;
    return StatusPill(
      label: low ? 'Check' : '${(confidence * 100).round()}%',
      background: low ? k.warnC : k.surf2,
      foreground: low ? k.warnInk : k.tx3,
      dotColor: low ? k.warn : null,
    );
  }
}

/// A stage line, a spinner and a Cancel that actually aborts the request.
class AiProgressView extends StatelessWidget {
  const AiProgressView({
    super.key,
    required this.title,
    required this.stage,
    required this.onCancel,
  });

  final String title;
  final String stage;
  final VoidCallback onCancel;

  @override
  Widget build(BuildContext context) {
    final k = context.t;
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 40),
      decoration: BoxDecoration(
        color: k.surf,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: k.bd),
      ),
      child: Column(
        children: [
          Container(
            width: 72,
            height: 72,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              color: k.priC,
              borderRadius: BorderRadius.circular(24),
            ),
            child: SizedBox(
              width: 30,
              height: 30,
              child: CircularProgressIndicator(strokeWidth: 3, color: k.priInk),
            ),
          ),
          const SizedBox(height: 16),
          Text(
            title,
            textAlign: TextAlign.center,
            style: const TextStyle(
              fontSize: 19,
              fontWeight: FontWeight.w800,
              letterSpacing: -0.2,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            stage,
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 14, height: 1.5, color: k.tx3),
          ),
          const SizedBox(height: 18),
          AppOutlinedButton(label: 'Cancel', height: 48, onPressed: onCancel),
        ],
      ),
    );
  }
}

/// The failure state every AI screen shows: the parent-readable message,
/// Try again when retrying could help, and a way out.
class AiFailureView extends StatelessWidget {
  const AiFailureView({
    super.key,
    required this.failure,
    required this.onRetry,
    required this.onCancel,
    this.title = "Gemini couldn't do that",
  });

  final AppFailure failure;
  final VoidCallback onRetry;
  final VoidCallback onCancel;
  final String title;

  @override
  Widget build(BuildContext context) => ErrorStateView(
    title: title,
    description: failure.message,
    actionLabel: failure.canRetry ? 'Try again' : 'Change settings',
    onAction: failure.canRetry
        ? onRetry
        : () => Navigator.of(context, rootNavigator: true).pushNamed(Routes.aiSettings),
    onCancel: onCancel,
  );
}

/// A count stepper row for the question mix.
class CountStepper extends StatelessWidget {
  const CountStepper({
    super.key,
    required this.label,
    required this.value,
    required this.onChanged,
    this.max = 40,
  });

  final String label;
  final int value;
  final ValueChanged<int> onChanged;
  final int max;

  @override
  Widget build(BuildContext context) {
    final k = context.t;
    return Row(
      children: [
        Expanded(
          child: Text(
            label,
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w600,
              color: value == 0 ? k.tx4 : k.tx,
            ),
          ),
        ),
        AppIconButton(
          size: 34,
          borderRadius: 10,
          background: k.surf2,
          onTap: value == 0 ? null : () => onChanged(value - 1),
          child: Text('−', style: TextStyle(fontSize: 18, color: k.tx2)),
        ),
        SizedBox(
          width: 36,
          child: Text(
            '$value',
            textAlign: TextAlign.center,
            style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w800),
          ),
        ),
        AppIconButton(
          size: 34,
          borderRadius: 10,
          background: k.priC,
          hoverBackground: k.priCH,
          onTap: value >= max ? null : () => onChanged(value + 1),
          child: StrokeIcon(AppIcons.plus, size: 16, color: k.priInk),
        ),
      ],
    );
  }
}
