// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-F1EkFX5k7Rid1xgs0yEMdM88gZ-XXxg',
    appId: '1:438761220028:android:873666ea701ca35af36db9',
    messagingSenderId: '438761220028',
    projectId: 'parent-academic-diary',
    storageBucket: 'parent-academic-diary.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZA-V4LvrM-jLvlVWRPRsZFmdZI3BJEYg',
    appId: '1:438761220028:ios:8385213d22a4ad57f36db9',
    messagingSenderId: '438761220028',
    projectId: 'parent-academic-diary',
    storageBucket: 'parent-academic-diary.firebasestorage.app',
    androidClientId: '438761220028-f298fdereol3mqbm4on134folgmc3d18.apps.googleusercontent.com',
    iosClientId: '438761220028-9n6n0pt0bi83g52cnsvc0lv937unmsfm.apps.googleusercontent.com',
    iosBundleId: 'com.parent.academic.diary',
  );
}
